name: saavy_music
description: An opinionated, compositional, and immutable music theory library for Dart, designed for developers who think about harmony in terms of shapes and relationships.
version: 0.4.0
repository: https://github.com/SaavyLab/saavy_music
homepage: https://github.com/SaavyLab/saavy_music
documentation: https://github.com/SaavyLab/saavy_music/blob/main/README.md

topics:
  - music-theory
  - ear-training
  - music
  - composition
  - harmony

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: '>=1.15.0 <2.0.0'
  meta: '>=1.3.0 <2.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
