name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
          cache: true

      - name: install dependencies
        run: dart pub get

      - name: analyze
        run: dart analyze

      - name: test
        run: dart test -r compact


